; Call-the-cops if failed attempted access 7 times
(define (make-account balance password)
  (let ((failed-access 0))
    (define (withdraw amount)
      (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (incorrect-password)
      (set! failed-access (+ failed-access 1))
      (if (= failed-access 7)
        (call-the-cops)
        "Incorrect password"))
    (define (call-the-cops)
      (set! failed-access 0)
      "the cops have been called")
    (lambda (pass m)
      (cond ((not (eq? pass password))
             (lambda (x) (incorrect-password)))
            ((eq? m 'withdraw) withdraw)
            ((eq? m 'deposit) deposit)
            (else (error "Unknown request -- MAKE-ACCOUNT" m))))))

(define acc (make-account 100 'secret-password))
((acc 'some-other-password 'withdraw) 50)
((acc 'some-other-password 'withdraw) 50)
((acc 'some-other-password 'withdraw) 50)
((acc 'some-other-password 'withdraw) 50)
((acc 'some-other-password 'withdraw) 50)
((acc 'some-other-password 'withdraw) 50)
((acc 'some-other-password 'withdraw) 50)
((acc 'secret-password 'withdraw) 50)
