(define (rand m)
  (let ((x random-init))
    (define (generate)
      (set! x (rand-update x))
      x)
    (define (reset new-value)
      (set! x new-value))
    (cond ((eq? m 'generate)
           (generate))
          ((eq? m 'reset)
           reset)
          (else (error "Unknown method -- RAND" m)))))
